// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/usecase/chat/chat_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:myapp/core/data/models/agreement.dart' as _i9;
import 'package:myapp/core/data/models/chat_channel.dart' as _i6;
import 'package:myapp/core/data/models/chat_message.dart' as _i7;
import 'package:myapp/core/data/models/user.dart' as _i11;
import 'package:myapp/core/data/repositories/agreement_repository.dart' as _i8;
import 'package:myapp/core/data/repositories/chat_repository.dart' as _i3;
import 'package:myapp/core/services/auth_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i3.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getChannelId(String? uid1, String? uid2) =>
      (super.noSuchMethod(
            Invocation.method(#getChannelId, [uid1, uid2]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getChannelId, [uid1, uid2]),
            ),
          )
          as String);

  @override
  _i5.Future<void> createChannel(_i6.ChatChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#createChannel, [channel]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.ChatChannel?> getChannel(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getChannel, [channelId]),
            returnValue: _i5.Future<_i6.ChatChannel?>.value(),
          )
          as _i5.Future<_i6.ChatChannel?>);

  @override
  _i5.Future<void> sendMessage(String? channelId, _i7.ChatMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [channelId, message]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<List<_i7.ChatMessage>> getMessagesStream(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesStream, [channelId]),
            returnValue: _i5.Stream<List<_i7.ChatMessage>>.empty(),
          )
          as _i5.Stream<List<_i7.ChatMessage>>);

  @override
  _i5.Future<List<_i6.ChatChannel>> listUserChannels(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#listUserChannels, [uid]),
            returnValue: _i5.Future<List<_i6.ChatChannel>>.value(
              <_i6.ChatChannel>[],
            ),
          )
          as _i5.Future<List<_i6.ChatChannel>>);

  @override
  _i5.Future<void> markMessagesAsRead(String? channelId, String? myUid) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [channelId, myUid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setTypingStatus(
    String? channelId,
    String? uid,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setTypingStatus, [channelId, uid, isTyping]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<Map<String, bool>> streamTypingStatus(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#streamTypingStatus, [channelId]),
            returnValue: _i5.Stream<Map<String, bool>>.empty(),
          )
          as _i5.Stream<Map<String, bool>>);
}

/// A class which mocks [AgreementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgreementRepository extends _i1.Mock
    implements _i8.AgreementRepository {
  MockAgreementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> createAgreement(_i9.Agreement? agreement) =>
      (super.noSuchMethod(
            Invocation.method(#createAgreement, [agreement]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateStatus(String? id, _i9.AgreementStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [id, status]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i9.Agreement?> getAgreement(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAgreement, [id]),
            returnValue: _i5.Future<_i9.Agreement?>.value(),
          )
          as _i5.Future<_i9.Agreement?>);

  @override
  _i5.Future<List<_i9.Agreement>> listByChannel(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#listByChannel, [channelId]),
            returnValue: _i5.Future<List<_i9.Agreement>>.value(
              <_i9.Agreement>[],
            ),
          )
          as _i5.Future<List<_i9.Agreement>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i2.User?>.empty(),
          )
          as _i5.Stream<_i2.User?>);

  @override
  _i5.Future<_i2.User?> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<_i2.User?>.value(),
          )
          as _i5.Future<_i2.User?>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i11.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i11.User?>.value(),
          )
          as _i5.Future<_i11.User?>);

  @override
  _i5.Future<_i11.User?> getCurrentUserModel() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserModel, []),
            returnValue: _i5.Future<_i11.User?>.value(),
          )
          as _i5.Future<_i11.User?>);

  @override
  _i5.Future<_i2.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i11.User?> register({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i11.User?>.value(),
          )
          as _i5.Future<_i11.User?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> reauthenticateWithCredential(
    _i2.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> changePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#resendEmailVerification, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> verify2FAPin(String? uid, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verify2FAPin, [uid, pin]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
