// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/usecase/skill_match/match_interaction_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:myapp/core/data/models/chat_channel.dart' as _i13;
import 'package:myapp/core/data/models/chat_message.dart' as _i14;
import 'package:myapp/core/data/models/match.dart' as _i10;
import 'package:myapp/core/data/models/match_result.dart' as _i7;
import 'package:myapp/core/data/models/user.dart' as _i5;
import 'package:myapp/core/data/repositories/block_repository.dart' as _i8;
import 'package:myapp/core/data/repositories/chat_repository.dart' as _i11;
import 'package:myapp/core/data/repositories/match_repository.dart' as _i9;
import 'package:myapp/core/services/auth_service.dart' as _i3;
import 'package:myapp/core/services/match_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.User?>.empty(),
          )
          as _i4.Stream<_i2.User?>);

  @override
  _i4.Future<_i2.User?> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<_i2.User?>.value(),
          )
          as _i4.Future<_i2.User?>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<_i5.User?> getCurrentUserModel() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserModel, []),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<_i2.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i5.User?> register({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reauthenticateWithCredential(
    _i2.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> changePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#resendEmailVerification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> verify2FAPin(String? uid, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verify2FAPin, [uid, pin]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [MatchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchService extends _i1.Mock implements _i6.MatchService {
  MockMatchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.MatchResult>> getRankedMatches(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getRankedMatches, [uid]),
            returnValue: _i4.Future<List<_i7.MatchResult>>.value(
              <_i7.MatchResult>[],
            ),
          )
          as _i4.Future<List<_i7.MatchResult>>);
}

/// A class which mocks [BlockRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockRepository extends _i1.Mock implements _i8.BlockRepository {
  MockBlockRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> blockUser(String? myUid, String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [myUid, targetUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unblockUser(String? myUid, String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#unblockUser, [myUid, targetUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getBlockedList(String? myUid) =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedList, [myUid]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Stream<List<String>> streamBlockedList(String? myUid) =>
      (super.noSuchMethod(
            Invocation.method(#streamBlockedList, [myUid]),
            returnValue: _i4.Stream<List<String>>.empty(),
          )
          as _i4.Stream<List<String>>);
}

/// A class which mocks [MatchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchRepository extends _i1.Mock implements _i9.MatchRepository {
  MockMatchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createMatch(_i10.Match? match) =>
      (super.noSuchMethod(
            Invocation.method(#createMatch, [match]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateMatchStatus(
    String? matchId,
    _i10.MatchStatus? status,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMatchStatus, [matchId, status, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i10.Match?> findMatchByParticipants(String? uid1, String? uid2) =>
      (super.noSuchMethod(
            Invocation.method(#findMatchByParticipants, [uid1, uid2]),
            returnValue: _i4.Future<_i10.Match?>.value(),
          )
          as _i4.Future<_i10.Match?>);

  @override
  _i4.Future<void> acceptMatch(String? myUid, String? peerUid) =>
      (super.noSuchMethod(
            Invocation.method(#acceptMatch, [myUid, peerUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> rejectMatch(String? myUid, String? peerUid) =>
      (super.noSuchMethod(
            Invocation.method(#rejectMatch, [myUid, peerUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> ignoreMatch(String? myUid, String? peerUid) =>
      (super.noSuchMethod(
            Invocation.method(#ignoreMatch, [myUid, peerUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveMatch(String? myUid, String? peerUid) =>
      (super.noSuchMethod(
            Invocation.method(#saveMatch, [myUid, peerUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.Match>> getUserMatches(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMatches, [uid]),
            returnValue: _i4.Future<List<_i10.Match>>.value(<_i10.Match>[]),
          )
          as _i4.Future<List<_i10.Match>>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i11.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getChannelId(String? uid1, String? uid2) =>
      (super.noSuchMethod(
            Invocation.method(#getChannelId, [uid1, uid2]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getChannelId, [uid1, uid2]),
            ),
          )
          as String);

  @override
  _i4.Future<void> createChannel(_i13.ChatChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#createChannel, [channel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i13.ChatChannel?> getChannel(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getChannel, [channelId]),
            returnValue: _i4.Future<_i13.ChatChannel?>.value(),
          )
          as _i4.Future<_i13.ChatChannel?>);

  @override
  _i4.Future<void> sendMessage(String? channelId, _i14.ChatMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [channelId, message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i14.ChatMessage>> getMessagesStream(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesStream, [channelId]),
            returnValue: _i4.Stream<List<_i14.ChatMessage>>.empty(),
          )
          as _i4.Stream<List<_i14.ChatMessage>>);

  @override
  _i4.Future<List<_i13.ChatChannel>> listUserChannels(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#listUserChannels, [uid]),
            returnValue: _i4.Future<List<_i13.ChatChannel>>.value(
              <_i13.ChatChannel>[],
            ),
          )
          as _i4.Future<List<_i13.ChatChannel>>);

  @override
  _i4.Future<void> markMessagesAsRead(String? channelId, String? myUid) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [channelId, myUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setTypingStatus(
    String? channelId,
    String? uid,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setTypingStatus, [channelId, uid, isTyping]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<Map<String, bool>> streamTypingStatus(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#streamTypingStatus, [channelId]),
            returnValue: _i4.Stream<Map<String, bool>>.empty(),
          )
          as _i4.Stream<Map<String, bool>>);
}
