// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-B5Gr3oNiTdM7Ir8M8iV8EPbHcLpvCpQ',
    appId: '1:889008953890:web:48e2d64c5b48fde69a487b',
    messagingSenderId: '889008953890',
    projectId: 'aptitude-5c28c',
    authDomain: 'aptitude-5c28c.firebaseapp.com',
    databaseURL: 'https://aptitude-5c28c-default-rtdb.firebaseio.com',
    storageBucket: 'aptitude-5c28c.firebasestorage.app',
    measurementId: 'G-J0PYLTJ7T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq1DtsyclRHNR9-L6KdVEqaFvjOK_tlRc',
    appId: '1:889008953890:android:9c27405c602f30b99a487b',
    messagingSenderId: '889008953890',
    projectId: 'aptitude-5c28c',
    databaseURL: 'https://aptitude-5c28c-default-rtdb.firebaseio.com',
    storageBucket: 'aptitude-5c28c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAriDVT6Qia2dMOY8nX5pvludlJ6m9Zw9M',
    appId: '1:889008953890:ios:26f3038b0d4940299a487b',
    messagingSenderId: '889008953890',
    projectId: 'aptitude-5c28c',
    databaseURL: 'https://aptitude-5c28c-default-rtdb.firebaseio.com',
    storageBucket: 'aptitude-5c28c.firebasestorage.app',
    iosClientId: '889008953890-lokqvnhc6011arid9pji2kl25bto42lc.apps.googleusercontent.com',
    iosBundleId: 'com.aptitude.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAriDVT6Qia2dMOY8nX5pvludlJ6m9Zw9M',
    appId: '1:889008953890:ios:26f3038b0d4940299a487b',
    messagingSenderId: '889008953890',
    projectId: 'aptitude-5c28c',
    databaseURL: 'https://aptitude-5c28c-default-rtdb.firebaseio.com',
    storageBucket: 'aptitude-5c28c.firebasestorage.app',
    iosClientId: '889008953890-lokqvnhc6011arid9pji2kl25bto42lc.apps.googleusercontent.com',
    iosBundleId: 'com.aptitude.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-B5Gr3oNiTdM7Ir8M8iV8EPbHcLpvCpQ',
    appId: '1:889008953890:web:4c787d39f54177719a487b',
    messagingSenderId: '889008953890',
    projectId: 'aptitude-5c28c',
    authDomain: 'aptitude-5c28c.firebaseapp.com',
    databaseURL: 'https://aptitude-5c28c-default-rtdb.firebaseio.com',
    storageBucket: 'aptitude-5c28c.firebasestorage.app',
    measurementId: 'G-4KZ0H9FQC8',
  );

}