class SkillCategories {
  SkillCategories._();

  static const Map<String, List<String>> categories = {
    'Technology': [
      'flutter',
      'dart',
      'python',
      'javascript',
      'typescript',
      'java',
      'swift',
      'kotlin',
      'coding',
      'programming',
      'web',
      'app',
      'mobile',
      'software',
      'development',
      'ai',
      'machine learning',
      'data',
      'database',
      'api',
      'backend',
      'frontend',
      'react',
      'angular',
      'vue',
      'node',
      'cloud',
      'devops',
      'security',
      'blockchain',
    ],
    'Music': [
      'guitar',
      'piano',
      'drums',
      'bass',
      'violin',
      'singing',
      'vocals',
      'production',
      'music theory',
      'composition',
      'songwriting',
      'recording',
      'mixing',
      'dj',
      'orchestra',
    ],
    'Art & Design': [
      'painting',
      'drawing',
      'sketching',
      'illustration',
      'photoshop',
      'design',
      'ui',
      'ux',
      'graphic',
      'animation',
      '3d',
      'blender',
      'figma',
      'sketch',
      'canva',
      'watercolor',
      'acrylic',
    ],
    'Languages': [
      'english',
      'spanish',
      'french',
      'german',
      'chinese',
      'japanese',
      'korean',
      'italian',
      'portuguese',
      'russian',
      'arabic',
      'grammar',
      'speaking',
      'conversation',
      'writing',
      'translation',
    ],
    'Sports & Fitness': [
      'yoga',
      'workout',
      'training',
      'football',
      'soccer',
      'basketball',
      'tennis',
      'swimming',
      'fitness',
      'pilates',
      'martial arts',
      'boxing',
      'running',
      'cycling',
      'strength',
      'cardio',
    ],
    'Cooking': [
      'cooking',
      'baking',
      'recipes',
      'cuisine',
      'meal prep',
      'nutrition',
      'pastry',
      'grilling',
      'vegan',
      'vegetarian',
      'sushi',
      'baking bread',
    ],
    'Business': [
      'marketing',
      'finance',
      'management',
      'startup',
      'entrepreneurship',
      'sales',
      'accounting',
      'investing',
      'strategy',
      'leadership',
      'project management',
      'consulting',
    ],
    'Science': [
      'physics',
      'chemistry',
      'biology',
      'mathematics',
      'calculus',
      'algebra',
      'engineering',
      'research',
      'statistics',
      'astronomy',
      'geology',
      'ecology',
    ],
    'Health & Wellness': [
      'meditation',
      'mental health',
      'therapy',
      'wellness',
      'self-care',
      'healing',
      'massage',
      'aromatherapy',
      'mindfulness',
      'stress',
    ],
    'Photography': [
      'photography',
      'videography',
      'editing',
      'camera',
      'lightroom',
      'photoshop',
      'composition',
      'lighting',
      'portrait',
      'landscape',
    ],
  };

  static List<String> suggest(String title, String description) {
    final text = '${title.toLowerCase()} ${description.toLowerCase()}';
    final matches = <MapEntry<String, int>>[];

    for (final entry in categories.entries) {
      final count =
          entry.value.where((keyword) => text.contains(keyword)).length;
      if (count > 0) {
        matches.add(MapEntry(entry.key, count));
      }
    }

    matches.sort((a, b) => b.value.compareTo(a.value));
    return matches.take(5).map((e) => e.key).toList();
  }
}
